RealEstate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import login, register, logout, dashboard

app_name='accounts'

urlpatterns = [
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),
    path('dashboard', dashboard, name='dashboard'),
]

listings/urls.py
from django.urls import path
from .views import index, listing, search

app_name='listings'

urlpatterns = [
    path('', index, name='listings'),
    path('<int:listing_id>', listing, name='listing'),
    path('search', search, name='search')
]

pages/urls.py
from django.urls import path
from .views import index, about

app_name='pages'

urlpatterns = [
    path('', index, name='index'),
    path('about', about, name='about')
]

templates/partials/_alertmsg.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container mt-4">
            <div class="alert alert-{{ message.tags }} text-center" role="alert">
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    This is a footer that contains nothing
</footer>

templates/partials/_navbar.html
{% load static %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'pages:index' %}">
            <img src="{% static 'img/logo.png' %}" class="logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li {% if '/' == request.path %}
                        class="nav-item active mr-3"
                    {% else %}
                        class="nav-item mr-3"
                    {% endif %}
                >
                    <a class="nav-link" href="{% url 'pages:index' %}">Home</a>
                </li>
                <li {% if 'about' in request.path %}
                        class="nav-item active mr-3"
                    {% else %}
                        class="nav-item mr-3"
                    {% endif %}
                >
                    <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                </li>
                <li {% if 'listings' in request.path %}
                        class="nav-item active mr-3"
                    {% else %}
                        class="nav-item mr-3"
                    {% endif %}
                >
                    <a class="nav-link" href="{% url 'listings:listings' %}">Featured Listings</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li {% if 'dashboard' in request.path %}
                            class="nav-item active mr-3"
                        {% else %}
                            class="nav-item mr-3"
                        {% endif %}
                    >
                        <a class="nav-link" href="{% url 'accounts:dashboard' %}">
                        <i class="fas fa-user mr-1"></i>{{ user.first_name }}</a>
                    </li>
                    <li>
                        <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">
                            <i class="fas fa-sign-out-alt"></i>Logout</a>
                        <form action="{% url 'accounts:logout' %}" method="post" id="logout">
                            {% csrf_token %}
                            <input type="hidden">
                        </form> 
                    </li>
                {% else %}
                    <li {% if 'register' in request.path %}
                            class="nav-item active mr-3"
                        {% else %}
                            class="nav-item mr-3"
                        {% endif %}
                    >
                        <a class="nav-link" href="{% url 'accounts:register' %}">
                        <i class="fas fa-user-plus"></i> Register</a>
                    </li>
                    <li {% if 'login' in request.path %}
                            class="nav-item active mr-3"
                        {% else %}
                            class="nav-item mr-3"
                        {% endif %}
                    >
                        <a class="nav-link" href="{% url 'accounts:login' %}">
                        <i class="fas fa-sign-in-alt"></i>Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/partials/_topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-3">
    <div class="container">
    <div class="row">
        <div class="col-md-4">
        <i class="fas fa-phone"></i> (617)-555-5555
        </div>
        <div class="col-md-4">
        <i class="fas fa-envelope-open"></i> contact@btrealestate.co
        </div>
        <div class="col-md-4">
        <div class="social text-right">
            <a href="#">
            <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
            <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
            <i class="fab fa-linkedin"></i>
            </a>
            <a href="#">
            <i class="fab fa-instagram"></i>
            </a>
            <a href="#">
            <i class="fab fa-pinterest"></i>
            </a>
        </div>
        </div>
    </div>
    </div>
</section>