RealEstate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('contacts/', include('contacts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from .views import contact

app_name='contacts'

urlpatterns = [
    path('contact', contact, name='contact'),
]

listings/urls.py
from django.urls import path
from .views import index, listing, search

app_name='listings'

urlpatterns = [
    path('', index, name='listings'),
    path('<int:listing_id>', listing, name='listing'),
    path('search', search, name='search')
]

pages/urls.py
from django.urls import path
from .views import index, about

app_name='pages'

urlpatterns = [
    path('', index, name='index'),
    path('about', about, name='about')
]

listings/models.py
from django.db import models
from django.db.models.base import Model
from datetime import datetime
from realtors.models import Realtor

class Listing(Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    garage = models.IntegerField(default=0)
    sqft = models.IntegerField()
    lot_size = models.DecimalField(max_digits=5, decimal_places=1)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title

listings/views.py
from django.shortcuts import render, get_object_or_404
from .models import Listing
from .choices import price_choices, state_choices, bedroom_choices

def index(request):
    listings = Listing.objects.all().order_by('-list_date')
    context = {
        'listings': listings
    }
    return render(request, 'listings/listings.html', context)

def listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    context = {
        'listing': listing
    }
    return render(request, 'listings/listing.html', context)

def search(request):
    queryset_list = Listing.objects.all().order_by('-list_date')

    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(description__icontains=keywords)

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(city__iexact=city)

    if 'state' in request.GET:
        state = request.GET['state']
        if state:
            queryset_list = queryset_list.filter(state__iexact=state)

    if 'bedrooms' in request.GET:
        bedrooms = request.GET['bedrooms']
        if bedrooms:
            queryset_list = queryset_list.filter(bedrooms__lte=bedrooms)

    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(price__lte=price)

    context = {
        'price_choices': price_choices,
        'bedroom_choices': bedroom_choices,
        'state_choices': state_choices,
        'listings': queryset_list,
        'values': request.GET
    }
    return render(request, 'listings/search.html', context)

templates/listings/listing.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} | {{ listing.title }}{% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
	<div class="container">
		<div class="row text-center">
			<div class="col-md-12">
				<h1 class="display-4">{{ listing.title }}</h1>
				<p class="lead">
					<i class="fas fa-map-marker"></i> {{ listing.city }} {{ listing.state }}, {{ listing.zipcode }}
				</p>
			</div>
		</div>
	</div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
	<div class="container">
		<nav>
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url 'pages:index' %}">Home</a>
				</li>
				<li class="breadcrumb-item">
					<a href="{% url 'listings:listings' %}">Listings</a>
				</li>
				<li class="breadcrumb-item active">{{ listing.title }}</li>
			</ol>
		</nav>
	</div>
</section>

{% include 'partials/_alertmsg.html' %}

<!-- Listing -->
<section id="listing" class="py-4">
	<div class="container">
		<a href="{% url 'listings:listings' %}" class="btn btn-light mb-4">Back To Listings</a>
		<div class="row">
			<div class="col-md-9">
				<!-- Home Main Image -->
				<img
					src="{{ listing.photo_main.url }}"
					alt=""
					class="img-main img-fluid mb-3"
				/>
				<!-- Thumbnails -->
				<div class="row mb-5 thumbs">
                    {% if listing.photo_1 %}
                        <div class="col-md-2">
                            <a
                                href="{{ listing.photo_1.url }}"
                                data-lightbox="home-images"
                            >
                                <img
                                    src="{{ listing.photo_1.url }}"
                                    alt=""
                                    class="img-fluid"
                                />
                            </a>
                        </div>
                    {% endif %}
                    {% if listing.photo_2 %}
                        <div class="col-md-2">
                            <a
                                href="{{ listing.photo_2.url }}"
                                data-lightbox="home-images"
                            >
                                <img
                                    src="{{ listing.photo_2.url }}"
                                    alt=""
                                    class="img-fluid"
                                />
                            </a>
                        </div>
                    {% endif %}
                    {% if listing.photo_3 %}
                        <div class="col-md-2">
                            <a
                                href="{{ listing.photo_3.url }}"
                                data-lightbox="home-images"
                            >
                                <img
                                    src="{{ listing.photo_3.url }}"
                                    alt=""
                                    class="img-fluid"
                                />
                            </a>
                        </div>
                    {% endif %}
                    {% if listing.photo_4 %}
                        <div class="col-md-2">
                            <a
                                href="{{ listing.photo_4.url }}"
                                data-lightbox="home-images"
                            >
                                <img
                                    src="{{ listing.photo_4.url }}"
                                    alt=""
                                    class="img-fluid"
                                />
                            </a>
                        </div>
                    {% endif %}
                    {% if listing.photo_5 %}
                        <div class="col-md-2">
                            <a
                                href="{{ listing.photo_5.url }}"
                                data-lightbox="home-images"
                            >
                                <img
                                    src="{{ listing.photo_5.url }}"
                                    alt=""
                                    class="img-fluid"
                                />
                            </a>
                        </div>
                    {% endif %}
                    {% if listing.photo_6 %}
                        <div class="col-md-2">
                            <a
                                href="{{ listing.photo_6.url }}"
                                data-lightbox="home-images"
                            >
                                <img
                                    src="{{ listing.photo_6.url }}"
                                    alt=""
                                    class="img-fluid"
                                />
                            </a>
                        </div>
                    {% endif %}
				</div>
				<!-- Fields -->
				<div class="row mb-5 fields">
					<div class="col-md-6">
						<ul class="list-group list-group-flush">
							<li class="list-group-item text-secondary">
								<i class="fas fa-money-bill-alt"></i> Asking
								Price:
								<span class="float-right">${{ listing.price | intcomma }}</span>
							</li>
							<li class="list-group-item text-secondary">
								<i class="fas fa-bed"></i> Bedrooms:
								<span class="float-right">{{ listing.bedrooms }}</span>
							</li>
							<li class="list-group-item text-secondary">
								<i class="fas fa-bath"></i> Bathrooms:
								<span class="float-right">{{ listing.bathrooms }}</span>
							</li>
							<li class="list-group-item text-secondary">
								<i class="fas fa-car"></i> Garage:
								<span class="float-right">{{ listing.garage }}</span>
							</li>
						</ul>
					</div>
					<div class="col-md-6">
						<ul class="list-group list-group-flush">
							<li class="list-group-item text-secondary">
								<i class="fas fa-th-large"></i> Square Feet:
								<span class="float-right">{{ listing.sqft }}</span>
							</li>
							<li class="list-group-item text-secondary">
								<i class="fas fa-square"></i> Lot Size:
								<span class="float-right">{{ listing.lot_size }}</span>
							</li>
							<li class="list-group-item text-secondary">
								<i class="fas fa-calendar"></i> Listing Date:
								<span class="float-right">{{ listing.list_date }}</span>
							</li>
							<li class="list-group-item text-secondary">
								<i class="fas fa-bed"></i> Realtor:
								<span class="float-right">{{ listing.realtor }}</span>
							</li>
						</ul>
					</div>
				</div>

				<!-- Description -->
				<div class="row mb-5">
					<div class="col-md-12">
						{{ listing.description }}
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="card mb-3">
					<img
						class="card-img-top"
						src="{{ listing.realtor.photo.url }}"
						alt=""
					/>
					<div class="card-body">
						<h5 class="card-title">Property Realtor</h5>
						<h6 class="text-secondary">{{ listing.realtor.name }}</h6>
					</div>
				</div>
				<button
					class="btn-primary btn-block btn-lg"
					data-toggle="modal"
					data-target="#inquiryModal"
				>
					Make An Inquiry
				</button>
			</div>
		</div>
	</div>
</section>

<!-- Inquiry Modal -->
<div class="modal fade" id="inquiryModal" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="inquiryModalLabel">
					Make An Inquiry
				</h5>
				<button type="button" class="close" data-dismiss="modal">
					<span>&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form action="{% url 'contacts:contact' %}" method="post">
					{% csrf_token %}
					<input type="hidden" name='listing' value="{{ listing.title }}"/>
					<input type="hidden" name='listing_id' value="{{ listing.id }}"/>
					{% if user.is_authenticated %}
						<input type="hidden" name='user_id' value="{{ user.id }}"/>
					{% else %}
						<input type="hidden" name='user_id' value="0"/>
					{% endif %}
					<input type="hidden" name='realtor_email' value="{{ listing.realtor.email }}"/>
					<input type="hidden" name='realtor_name' value="{{ listing.realtor.name }}"/>
					<div class="form-group">
						<label for="property_name" class="col-form-label"
							>Property:</label
						>
						<input
							type="text"
							name="listing"
							class="form-control"
							value="{{ listing.title }}"
							disabled
						/>
					</div>
					<div class="form-group">
						<label for="name" class="col-form-label">Name:</label>
						<input
							type="text"
							name="name"
							class="form-control"
							{% if user.is_authenticated %}
								value="{{ user.first_name }} {{ user.last_name }}"
							{% endif %}
							required
						/>
					</div>
					<div class="form-group">
						<label for="email" class="col-form-label">Email:</label>
						<input
							type="email"
							name="email"
							class="form-control"
							{% if user.is_authenticated %}
								value="{{ user.email }}"
							{% endif %}
							required
						/>
					</div>
					<div class="form-group">
						<label for="phone" class="col-form-label">Phone:</label>
						<input type="text" name="phone" class="form-control" />
					</div>
					<div class="form-group">
						<label for="message" class="col-form-label"
							>Message:</label
						>
						<textarea
							name="message"
							class="form-control"
						></textarea>
					</div>
					<hr />
					<input
						type="submit"
						value="Send"
						class="btn btn-block btn-secondary"
					/>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/listings/listings.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} | Listings{% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
        <div class="col-md-12">
            <h1 class="display-4">Browse Our Properties</h1>
            <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
        </div>
        </div>
    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
                <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active"> Browse Listings</li>
        </ol>
        </nav>
    </div>
</section>

<!-- Listings -->
<section id="listings" class="py-4">
    <div class="container">
        <div class="row">
            {% if listings %}
                {% for listing in listings %}
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card listing-preview">
                        <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="">
                        <div class="card-img-overlay">
                            <h2>
                            <span class="badge badge-secondary text-white">${{ listing.price | intcomma }}</span>
                            </h2>
                        </div>
                        <div class="card-body">
                            <div class="listing-heading text-center">
                            <h4 class="text-primary">{{ listing.title }}</h4>
                            <p>
                                <i class="fas fa-map-marker text-secondary"></i>{{ listing.city }} {{ listing.state }}, {{ listing.zipcode }}</p>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                            <div class="col-6">
                                <i class="fas fa-th-large"></i> Sqft: {{ listing.sqft }}</div>
                            <div class="col-6">
                                <i class="fas fa-car"></i> Garage: {{ listing.garage }}</div>
                            </div>
                            <div class="row py-2 text-secondary">
                            <div class="col-6">
                                <i class="fas fa-bed"></i> Bedrooms: {{ listing.bedrooms }}</div>
                            <div class="col-6">
                                <i class="fas fa-bath"></i> Bathrooms: {{ listing.bathrooms }}</div>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                            <div class="col-12">
                                <i class="fas fa-user"></i> {{ listing.realtor }}</div>
                            </div>
                            <div class="row text-secondary pb-2">
                            <div class="col-6">
                                <i class="fas fa-clock"></i> {{ listing.list_date | timesince }}</div>
                            </div>
                            <hr>
                            <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                        </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="class-md-12">
                    <p>No listings available</p>
                </div>
            {% endif %}
        </div>

        <div class="row">
        <div class="col-md-12">
            <ul class="pagination">
            <li class="page-item disabled">
                <a class="page-link" href="#">&laquo;</a>
            </li>
            <li class="page-item active">
                <a class="page-link" href="#">1</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">3</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">&raquo;</a>
            </li>
            </ul>
        </div>
        </div>
    </div>
</section>
{% endblock %}

templates/listings/search.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %} | Search{% endblock %}

{% block content %}
<section id="showcase-inner" class="showcase-search text-white py-5">
	<div class="container">
		<div class="row text-center">
			<div class="col-md-12">
				<form action="{% url 'listings:search' %}">
					<!-- Form Row 1 -->
					<div class="form-row">
						<div class="col-md-4 mb-3">
							<label class="sr-only">Keywords</label>
							<input
								type="text"
								name="keywords"
								class="form-control"
								placeholder="Keyword (Pool, Garage, etc)"
								value="{{ values.keywords }}"
							/>
						</div>

						<div class="col-md-4 mb-3">
							<label class="sr-only">City</label>
							<input
								type="text"
								name="city"
								class="form-control"
								placeholder="City"
								value="{{ values.city }}"
							/>
						</div>

						<div class="col-md-4 mb-3">
							<label class="sr-only">State</label>
							<select name="state" class="form-control">
								<option selected="true" disabled="disabled">
									State (All)
								</option>
								{% for key, value in state_choices.items %}
                        			<option value="{{ key }}"
										{% if key == values.state %}
											selected
										{% endif %}
									>{{ value }}</option>
                    			{% endfor %}	
							</select>
						</div>
					</div>
					<!-- Form Row 2 -->
					<div class="form-row">
						<div class="col-md-6 mb-3">
							<label class="sr-only">Bedrooms</label>
							<select name="bedrooms" class="form-control">
								<option selected="true" disabled="disabled">
									Bedrooms (Any)
								</option>
								{% for key, value in bedroom_choices.items %}
									<option value="{{ key }}"
										{% if key == values.bedrooms %}
											selected
										{% endif %}
									>{{ value }}</option>
								{% endfor %}
							</select>
						</div>
						<div class="col-md-6 mb-3">
							<select name="price" class="form-control">
								<option selected="true" disabled="disabled">
									Max Price (All)
								</option>
								{% for key, value in price_choices.items %}
									<option value="{{ key }}"
										{% if key == values.price %}
											selected
										{% endif %}
									>{{ value }}</option>
								{% endfor %}
							</select>
						</div>
					</div>
					<button
						class="btn btn-secondary btn-block mt-4"
						type="submit"
					>
						Submit form
					</button>
				</form>
			</div>
		</div>
	</div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
	<div class="container">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url 'pages:index' %}"> <i class="fas fa-home"></i> Home</a>
				</li>
				<li class="breadcrumb-item">
					<a href="{% url 'listings:listings' %}">Browse Listings</a>
				</li>
				<li class="breadcrumb-item active">Search Results</li>
			</ol>
		</nav>
	</div>
</section>

<!-- Listings -->
<section id="listings" class="py-4">
	<div class="container">
		<div class="row">
			{% if listings %}
                {% for listing in listings %}
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card listing-preview">
                        <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="">
                        <div class="card-img-overlay">
                            <h2>
                            <span class="badge badge-secondary text-white">${{ listing.price | intcomma }}</span>
                            </h2>
                        </div>
                        <div class="card-body">
                            <div class="listing-heading text-center">
								<h4 class="text-primary">{{ listing.title }}</h4>
								<p>
									<i class="fas fa-map-marker text-secondary"></i>{{ listing.city }} {{ listing.state }}, {{ listing.zipcode }}</p>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
								<div class="col-6">
									<i class="fas fa-th-large"></i> Sqft: {{ listing.sqft }}</div>
								<div class="col-6">
									<i class="fas fa-car"></i> Garage: {{ listing.garage }}</div>
                            </div>
                            <div class="row py-2 text-secondary">
								<div class="col-6">
									<i class="fas fa-bed"></i> Bedrooms: {{ listing.bedrooms }}</div>
								<div class="col-6">
									<i class="fas fa-bath"></i> Bathrooms: {{ listing.bathrooms }}</div>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
								<div class="col-12">
									<i class="fas fa-user"></i> {{ listing.realtor }}</div>
                            </div>
                            <div class="row text-secondary pb-2">
								<div class="col-6">
									<i class="fas fa-clock"></i> {{ listing.list_date | timesince }}</div>
                            </div>
                            <hr>
                            <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                        </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-md-12">
                    <p>No listings available</p>
                </div>
            {% endif %}
		</div>
	</div>
</section>
{% endblock %}